package md.borisveriga.bpodcat.core.model

import java.net.URLDecoder

/**
 * What the user pasted into the "add show" field, once classified.
 */
sealed interface PodcastLink {

    /**
     * An Apple Podcasts show, identified by its numeric collection id.
     *
     * The RSS feed still has to be resolved through the iTunes lookup endpoint.
     *
     * @property itunesId Apple's `collectionId`.
     */
    data class Apple(val itunesId: Long) : PodcastLink

    /**
     * A direct RSS feed URL, usable without any Apple round trip.
     *
     * @property feedUrl the feed URL, trimmed.
     */
    data class Rss(val feedUrl: String) : PodcastLink

    /**
     * A public YouTube playlist, to be read through YouTube's Atom feed and played as audio only.
     *
     * @property playlistId the canonical `PL…` / `UU…` / `FL…` / `OLAK5uy_…` id, case preserved.
     */
    data class YouTubePlaylist(val playlistId: String) : PodcastLink
}

/**
 * Classifies pasted text into a [PodcastLink].
 *
 * Apple Podcasts URLs carry the show id in the last path segment, after every localisable part:
 *
 * ```
 * https://podcasts.apple.com/us/podcast/podlodka-podcast/id1209828744
 * https://podcasts.apple.com/us/podcast/%D1%80%D0%B0%D0%B4%D0%B8%D0%BE-%D1%82/id256504435
 * ```
 *
 * Only the `id<digits>` segment is read, so the percent-encoded Cyrillic slugs, the country code and
 * any `?i=<episode id>` query are all irrelevant.
 *
 * YouTube playlist links carry the id in a `list=` query parameter, and the same playlist has many
 * spellings — a watch page with a playlist attached, the playlist page itself, a `youtu.be` short
 * link, the mobile and music hosts. All of them must reduce to one id, because that id becomes the
 * feed URL, which becomes the [podcastIdOf] hash and the uniqueness key. If two spellings survived,
 * pasting the same playlist twice would produce two shows.
 *
 * Branch order is load-bearing: Apple first (so `music.apple.com` is never confused with
 * `music.youtube.com`), YouTube second, and the permissive "any `http(s)` URL is an RSS feed"
 * fallback last.
 */
object PodcastLinkParser {

    /** Matches the `/id1209828744` path segment of an Apple Podcasts URL. */
    private val APPLE_ID_REGEX = Regex("""/id(\d+)""")

    /** Matches a bare Apple collection id pasted on its own, e.g. `1209828744`. */
    private val BARE_ID_REGEX = Regex("""^\d{6,}$""")

    /** Hosts whose URLs carry an Apple collection id. */
    private val APPLE_HOSTS = listOf("podcasts.apple.com", "itunes.apple.com", "music.apple.com")

    /** Hosts that serve YouTube playlists, after `www.`/`m.`/`music.` has been stripped. */
    private val YOUTUBE_HOSTS = setOf("youtube.com", "youtu.be")

    /** Subdomains that front the same content and can be dropped before comparing hosts. */
    private val YOUTUBE_SUBDOMAINS = listOf("www.", "m.", "music.")

    /** Pulls the playlist id out of a `list=` (watch and playlist pages) query parameter. */
    private val LIST_PARAM_REGEX = Regex("""[?&]list=([^&#]+)""")

    /** Pulls the playlist id out of a `playlist_id=` (Atom feed) query parameter. */
    private val FEED_PARAM_REGEX = Regex("""[?&]playlist_id=([^&#]+)""")

    /**
     * Shapes of playlist id we accept.
     *
     * `PL` user playlists, `UU` channel-uploads playlists, `FL` favourites and `OLAK5uy_` album
     * playlists all have durable Atom feeds. Everything else — `WL` (Watch Later), `LL` (Liked) and
     * the `RD`/`RDMM` autogenerated mixes — is either private or regenerated per viewer, and its
     * feed 404s or comes back empty, so it is rejected here rather than after a wasted fetch.
     */
    private val PLAYLIST_ID_REGEX = Regex("""^(PL|UU|FL|OLAK5uy_)[A-Za-z0-9_-]{10,}$""")

    /**
     * Classifies [input].
     *
     * @param input raw text from the "add show" field.
     * @return the classified link, or `null` if [input] is none of an Apple link, a bare Apple id, a
     *   YouTube playlist link, a bare playlist id, or an `http(s)` URL.
     */
    fun parse(input: String): PodcastLink? {
        val trimmed = input.trim()
        if (trimmed.isEmpty()) return null

        if (BARE_ID_REGEX.matches(trimmed)) {
            return trimmed.toLongOrNull()?.let(PodcastLink::Apple)
        }

        // A bare playlist id can never collide with a bare Apple id: Apple's is all digits, and
        // every playlist id we accept starts with letters.
        if (PLAYLIST_ID_REGEX.matches(trimmed)) {
            return PodcastLink.YouTubePlaylist(trimmed)
        }

        val lowercase = trimmed.lowercase()
        val isAppleHost = APPLE_HOSTS.any { host -> lowercase.contains(host) }
        if (isAppleHost) {
            val id = APPLE_ID_REGEX.find(trimmed)?.groupValues?.get(1)?.toLongOrNull()
            // An Apple URL without an id (a genre or charts page) is not addable.
            return id?.let(PodcastLink::Apple)
        }

        if (isYouTubeUrl(trimmed)) {
            // A YouTube URL naming no usable playlist is *not* an RSS feed. Returning null rather
            // than falling through keeps the repository from fetching a watch page and reporting
            // "Document contains no <channel> element" to the user.
            return playlistIdOf(trimmed)?.let(PodcastLink::YouTubePlaylist)
        }

        if (lowercase.startsWith("http://") || lowercase.startsWith("https://")) {
            return PodcastLink.Rss(trimmed)
        }

        return null
    }

    /**
     * Whether [url] points at YouTube.
     *
     * The host is compared by *equality* after stripping the scheme and the interchangeable
     * `www.`/`m.`/`music.` subdomains. A substring test would also match a URL such as
     * `https://evil.example/?u=youtube.com`, which would then be classified as YouTube instead of
     * being fetched as the feed it claims to be.
     *
     * Exposed because the repository needs the same test to tell a YouTube link that names no
     * playlist apart from an ordinary feed URL.
     *
     * @param url the trimmed input.
     */
    fun isYouTubeUrl(url: String): Boolean {
        val lowercase = url.lowercase()
        val withoutScheme = when {
            lowercase.startsWith("https://") -> lowercase.removePrefix("https://")
            lowercase.startsWith("http://") -> lowercase.removePrefix("http://")
            else -> return false
        }

        var host = withoutScheme.substringBefore('/').substringBefore('?').substringBefore('#')
        for (subdomain in YOUTUBE_SUBDOMAINS) {
            if (host.startsWith(subdomain)) {
                host = host.removePrefix(subdomain)
                break
            }
        }
        return host in YOUTUBE_HOSTS
    }

    /**
     * Extracts the canonical playlist id from a YouTube URL.
     *
     * @param url a URL already known to be on a YouTube host.
     * @return the playlist id, or `null` when the URL names no playlist (a bare watch page, a
     *   channel page) or names one with no durable feed (Watch Later, Liked, an autogenerated mix).
     */
    private fun playlistIdOf(url: String): String? {
        val raw = LIST_PARAM_REGEX.find(url)?.groupValues?.get(1)
        // Already-canonical feed URLs round-trip, so re-adding a stored feedUrl is a no-op.
            ?: FEED_PARAM_REGEX.find(url)?.groupValues?.get(1)
            ?: return null

        val decoded = runCatching { URLDecoder.decode(raw, Charsets.UTF_8.name()) }.getOrDefault(raw)
        // music.youtube.com prefixes playlist ids with "VL" ("view list") in its own links.
        val candidate = decoded.removePrefix("VL")

        return candidate.takeIf(PLAYLIST_ID_REGEX::matches)
    }
}
